Metrics/LineLength:
  Max: 215

Metrics/MethodLength:
  Max: 60

Mertrcs/ClassLength:
  Max: 150

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false