AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "bin/**/*"
    - "db/**/*"

Metrics/LineLength:
  Max: 215

Metrics/MethodLength:
  Max: 60

Metrics/ClassLength:
  Max: 150

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# Some blocks are longer.
Metrics/BlockLength:
  ExcludedMethods:
    - "namespace"
    - "create_table"
  Exclude:
    - "config/**/*.rb"
    - "spec/**/*.rb"