version: '2'
services:
  web:
    build: .
    command: bundle exec foreman start -f Procfile.dev
    ports:
      - "3333:3333"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: mysql:5.5
    environment:
      MYSQL_DATABASE: im_development
      MYSQL_ROOT_PASSWORD: password