version: '2'
volumes:
  db-data:
    driver: local
services:
  web:
    build: .
    image: mobile_web:dev
    command: bundle exec rails s -b '0.0.0.0'
    env_file:
      - .env
    ports:
      - "3210:3000"
    links:
      - db
      - redis
    volumes:
      - .:/app
  worker:
    build: .
    image: mobile_worker:dev
    command: bundle exec sidekiq
    env_file:
      - .env
    links:
      - db
      - redis
    volumes:
      - .:/app
  db:
    image: mysql:5.5
    env_file:
      - .env
    ports:
      - "13366:3306"
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis
