version: '2'
services:
  app:
    build: .
    environment:
      - JOB_WORKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
  web:
    extends:
      service: app
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - "3210:3000"
    links:
      - db
      - redis
    volumes:
      - .:/app
  worker:
    extends:
      service: app
    command: bundle exec sidekiq
    links:
      - db
      - redis
    volumes:
      - .:/app
  db:
    image: mysql:5.5
    environment:
      - MYSQL_DATABASE=im_development
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis
volumes:
  db-data:
    driver: local