version: '2.1'

x-defaults: &defaults
  restart: unless-stopped
  build: .
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
  env_file: .env
  environment:
    ZEALOT_REDIS_HOST: redis
    ZEALOT_POSTGRES_HOST: postgres
  volumes:
    - .:/app:cached

services:
  redis:
    image: redis:5-alpine
    command: redis-server
    ports:
      - "16379:6379"
    volumes:
      - redis:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ze@l0t
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
  # adminer:
  #   image: adminer
  #   environment:
  #     ADMINER_DEFAULT_SERVER: postgres
  #   ports:
  #     - "18080:8080"
  web:
    <<: *defaults
    command: [ "run_server" ]
    ports:
      - "13000:3000"
  worker:
    <<: *defaults
    command: [ "run_worker" ]

volumes:
  redis:
  postgres: