version: "2.1"

services:
  redis:
    image: redis:4.0-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "redis:/var/lib/redis/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 30
  mysql:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "zealot"
    ports:
      - "13366:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  web:
    build: .
    image: zealot
    env_file:
      - .env
    ports:
      - "3210:3000"
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
  sidekiq:
    build: .
    image: zealot
    command: bundle exec sidekiq
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy

volumes:
  redis:
  mysql: