version: '2'
volumes:
  db-data:
    driver: local
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-production
    image: mobile_app:edge
    environment:
      - JOB_WORKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - MYSQL_DATABASE=im_staging
      - MYSQL_ROOT_PASSWORD=password
      - RAILS_ENV=staging
    volumes:
      - db-data:/var/lib/mysql
      - .:/app
  lb:
    image: traefik
    command: --web --docker --docker.domain=2b6.me --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./config/traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: mobile_web:edge
    command: bundle exec puma -C config/puma.rb
    links:
      - db
      - redis
    labels:
      - "traefik.backend=web"
      - "traefik.frontend.rule=Host:mobile.2b6.me"
    extends:
      service: app
    volumes_from:
      - app
  worker:
    image: mobile_worker:edge
    command: bundle exec sidekiq
    links:
      - db
      - redis
    extends:
      service: app
    volumes_from:
      - app
  db:
    image: mysql:5.5
    ports:
      - "3366:3306"
    volumes_from:
      - app
  redis:
    image: redis
