version: '2'

services:
  redis:
    image: redis:4.0-alpine
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  mysql:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'qmobile'
    ports:
      - "13366:3306"
    volumes:
      - 'mysql:/var/lib/mysql'
  web:
    depends_on:
      - redis
      - mysql
    build: .
    image: mobile_web:dev
    env_file:
      - .env
    ports:
      - "3210:3000"
    volumes:
      - .:/app
  sidekiq:
    depends_on:
      - redis
      - mysql
    build: .
    image: mobile_worker:dev
    command: bundle exec sidekiq
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  redis:
  mysql: