version: '2.1'

x-defaults: &defaults
  restart: unless-stopped
  build: .
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
  env_file: .env
  environment:
    ZEALOT_REDIS_HOST: redis
    ZEALOT_POSTGRES_HOST: postgres
  volumes:
    - .:/app:cached

services:
  redis:
    image: redis:4.0-alpine
    command: redis-server
    ports:
      - "16379:6379"
    volumes:
      - redis:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 30
  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    <<: *defaults
    ports:
      - "10080:3000"
  worker:
    <<: *defaults
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml.erb"]

volumes:
  redis:
  postgres: