default: &default
  adapter: mysql2
  encoding: utf8
  pool: 20
  username: <%= ENV['MYSQL_USERNAME'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || '' %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>
  database: <%= (host = ENV['MYSQL_DB_NAME'] || 'zealot'; case ENV['RAILS_ENV'] when 'test' then "#{host}_test"; when 'production' then host else "#{host}_development"; end) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default